# Generated by Django 3.1.2 on 2020-10-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'empmodel',
            },
        ),
    ]
